consul:
  image: qnib/consul
  ports:
   - "8500:8500"
  environment:
   - DC_NAME=dc1
   - CONSUL_BOOTSTRAP=true
  dns: 127.0.0.1
  hostname: consul
  container_name: consul
  privileged: true

ipfs:
  image: qnib/ipfs
  environment:
   - dc_name=dc1
  dns: 127.0.0.1
  volumes:
   - /data/
  ports:
   - 5001
   - 8080
  privileged: true
